sudo: false
language: node_js

node_js:
  - "4.1"
  - "4.0"

before_script:
  - npm install -g eslint eslint-plugin-flow-vars babel-eslint eslint-plugin-standard eslint-plugin-promise

script:
  - npm build
  - eslint lib/
