sudo: false
language: node_js

node_js:
  - "4.4"

before_script:
  - npm install -g eslint eslint-plugin-flow-vars babel-eslint eslint-plugin-standard eslint-plugin-promise flow-bin

script:
  - cp package-node.json package.json && npm install && cp package-browser.json package.json && npm install && rm package.json
  - make check 
  - make .move-in-node .build-node .cleanup-node
  - make .move-in-browser .build- .cleanup-browser
